services:
  postgres:
    image: postgres:15-alpine
    container_name: dungeon-game-db
    environment:
      POSTGRES_DB: dungeon_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dungeon-network

  app:
    build: .
    container_name: dungeon-game-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dungeon_game
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
      SHOW_SQL: false
      LOG_LEVEL: INFO
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dungeon-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/gatling_rules.yml:/etc/prometheus/gatling_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - dungeon-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboard-configs:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - dungeon-network

  gatling-exporter:
    image: prom/pushgateway:latest
    container_name: gatling-exporter
    ports:
      - "9091:9091"
    networks:
      - dungeon-network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  dungeon-network:
    driver: bridge
